const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DB='mikhael-v5',VER=2,STORE='profiles',META='meta';
const DEFAULT={day:1,completedDays:[],sessions:0,activeDays:[],streak:0,lastActive:null,skills:{comprension:0,pronunciacion:0,lectura:0,produccion:0,gramatica:0},cards:{},history:[],exerciseHistory:[],settings:{largeText:false,reduceMotion:false,haptic:true}};
let D={},state=structuredClone(DEFAULT),profileId=null,profileName='';
let lesson={day:1,step:0,question:null,answered:false,revealed:false};
let review={queue:[],cursor:0,ratings:{}};let currentView='home';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0591-\u05C7]/g,'').replace(/\s+/g,'').trim();
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE);if(!db.objectStoreNames.contains(META))db.createObjectStore(META)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function metaGet(k){const db=await openDB();return new Promise(res=>{const q=db.transaction(META).objectStore(META).get(k);q.onsuccess=()=>res(q.result)})}
async function metaPut(k,v){const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction(META,'readwrite').objectStore(META).put(v,k);q.onsuccess=res;q.onerror=()=>rej(q.error)})}
async function dbGet(){if(!profileId)return null;const db=await openDB();return new Promise(res=>{const q=db.transaction(STORE).objectStore(STORE).get(profileId);q.onsuccess=()=>res(q.result||null)})}
async function dbPut(){const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).put(state,profileId);q.onsuccess=res;q.onerror=()=>rej(q.error)})}
async function initProfiles(){let p=await metaGet('profiles')||[],a=await metaGet('activeProfile');if(!p.length){const id='p_'+Date.now();p=[{id,name:'Mi perfil',createdAt:Date.now()}];a=id;await metaPut('profiles',p);await metaPut('activeProfile',a)}profileId=a||p[0].id;const x=p.find(z=>z.id===profileId)||p[0];profileId=x.id;profileName=x.name;const old=await dbGet();if(old)state={...structuredClone(DEFAULT),...old,skills:{...DEFAULT.skills,...old.skills},settings:{...DEFAULT.settings,...old.settings},exerciseHistory:old.exerciseHistory||[]}}
async function load(){const names=['block1-content','alphabet','vocalization','reader','morphology','grammar'];const vals=await Promise.all(names.map(n=>fetch(`./data/${n}.json`).then(r=>{if(!r.ok)throw Error(`No se pudo cargar ${n}.json`);return r.json()})));[D.curr,D.alphabet,D.vocal,D.reader,D.morph,D.grammar]=vals;D.vocab=D.curr.vocab;D.units=D.curr.units;D.sessions=D.curr.sessions;D.phrases=D.curr.phrases;D.ctxGrammar=D.curr.contextualGrammar;D.exerciseMap=D.curr.exercises||{}}
function today(){return new Date().toISOString().slice(0,10)}
function touch(){const d=today();if(!state.activeDays.includes(d))state.activeDays.push(d);if(state.lastActive!==d){const y=new Date();y.setDate(y.getDate()-1);state.streak=state.lastActive===y.toISOString().slice(0,10)?state.streak+1:1;state.lastActive=d}}
function unitForDay(day){return D.units.find(u=>u.days.includes(day))||null}
function sessionForDay(day){return D.sessions.find(s=>s.day===day)||null}
function vocab(id){return D.vocab.find(v=>v.id===id)}
function phrase(id){return D.phrases.find(p=>p.id===id)}
function grammar(id){return D.ctxGrammar.find(g=>g.id===id)}
function card(id){return state.cards[id]||(state.cards[id]={id,created:Date.now(),last:null,due:Date.now(),interval:0,ease:2.5,reps:0,errors:0,state:'new'})}
function introduce(ids){ids.filter(Boolean).forEach(id=>{if(vocab(id))card(id)})}
function due(){const n=Date.now();return D.vocab.filter(v=>state.cards[v.id]?.due<=n)}
function score(v){const c=state.cards[v.id];if(!c)return 0;const overdue=Math.max(0,(Date.now()-(c.due||0))/3600000);return overdue*5+c.errors*18+(2.5-c.ease)*15-c.reps*.25}
function save(){return dbPut().then(renderGlobal)}
function show(v){currentView=v;$$('.view').forEach(x=>x.classList.toggle('hidden',x.id!==v));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='course')renderCourse();if(v==='review')renderReview();if(v==='reader')renderReader();if(v==='alphabet')renderAlphabet();if(v==='grammar')renderGrammar();if(v==='stats')renderStats();if(v==='settings')renderProfilePanel();renderGlobal();scrollTo({top:0,behavior:'auto'})}
function renderGlobal(){const d=due().length;$('#profileName').textContent=profileName;$('#dueBadge').textContent=d;$('#mobileDue').textContent=d;$('#homeDay').textContent=state.day;$('#homeDue').textContent=d;$('#homeDueInline').textContent=d;$('#homeStreak').textContent=state.streak;const s=sessionForDay(state.day);$('#homeGoal').textContent=s?.objective||'Ruta posterior en construcción';$('#dayProgress').style.width=Math.round(state.completedDays.length/180*100)+'%';$('#sessionSummary').textContent=`${state.completedDays.length} de 180 días completados.`;$('#adaptiveAdvice').textContent=d?`Tienes ${d} tarjetas pendientes. Se priorizan las que más necesitan recuperación.`:'Continúa con la sesión del día.'}
function focusIds(s,u){const ids=[...(s.targetVocab||[]),...(s.reviewVocab||[])];if(ids.length)return [...new Set(ids)].map(vocab).filter(Boolean);return [...new Set([...(u.newVocab||[]).slice(0,4)])].map(vocab).filter(Boolean)}
function linkedPhrase(s){const ids=s?.phraseIds||[];return ids.map(phrase).find(Boolean)||null}
function currentGrammar(s,u){const ids=s?.contextualGrammarIds||u?.contextualGrammar||[];return ids.map(grammar).find(Boolean)||null}
function distractorMeanings(correctId,count=3){const pool=shuffle(D.vocab.filter(v=>v.id!==correctId&&v.meaning));return pool.slice(0,count).map(v=>v.meaning)}
function distractorHebrew(correctId,count=3){const pool=shuffle(D.vocab.filter(v=>v.id!==correctId));return pool.slice(0,count).map(v=>v.form)}
function ensureFour(correct,others){return shuffle([correct,...others.filter(x=>x!==correct).slice(0,3)]).slice(0,4)}
function targetForStep(s,u){const ids=[...(s.targetVocab||[]),...(s.reviewVocab||[])];const available=ids.map(vocab).filter(Boolean);if(available.length)return available;return (u.newVocab||[]).map(vocab).filter(Boolean)}
function buildQuestion(step,s,u){const words=targetForStep(s,u);const p=linkedPhrase(s);const g=currentGrammar(s,u);if(step===0){
  if(p)return {kind:'comprehension',title:'Comprensión',instruction:'Lee la frase y elige la traducción que corresponde.',he:p.text,correct:p.translation,options:ensureFour(p.translation,D.phrases.filter(x=>x.id!==p.id).map(x=>x.translation))};
  const v=words[0]; if(v)return {kind:'comprehension',title:'Comprensión',instruction:'Observa la forma hebrea y elige qué significa.',he:v.form,correct:v.meaning,options:ensureFour(v.meaning,distractorMeanings(v.id))};
  return {kind:'comprehension',title:'Comprensión',instruction:'Reconoce la dirección básica de lectura.',he:'אֵל  ←  לֵא',correct:'El hebreo se lee de derecha a izquierda.',options:ensureFour('El hebreo se lee de derecha a izquierda.',['El hebreo se lee de izquierda a derecha.','Las vocales se leen antes de las consonantes.','Cada palabra se lee siempre al revés.'])};
}
if(step===1){const v=words[step%Math.max(1,words.length)]||words[0];if(!v)return null;return {kind:'recognition',title:'Reconocimiento',instruction:'Mira la palabra hebrea sin traducción y selecciona su significado.',he:v.form,correct:v.meaning,options:ensureFour(v.meaning,distractorMeanings(v.id))};}
if(step===2){const v=words[(step+1)%Math.max(1,words.length)]||words[0];if(!v)return null;return {kind:'production',title:'Producción',instruction:`Escribe en hebreo la palabra que significa «${v.meaning}».`,prompt:v.meaning,correct:v.form,translit:v.translit||'—'};}
if(step===3&&g)return {kind:'grammar',title:'Gramática en contexto',instruction:`¿Qué afirmación explica mejor «${g.title}»?`,prompt:g.phenomenon,correct:g.explanation,options:ensureFour(g.explanation,D.ctxGrammar.filter(x=>x.id!==g.id).map(x=>x.explanation))};
if(step===3){return {kind:'grammar',title:'Gramática en contexto',instruction:'¿Qué debes observar en esta unidad?',prompt:u.patterns?.[0]||'el patrón trabajado',correct:'La relación entre la forma y su función dentro del contexto.',options:ensureFour('La relación entre la forma y su función dentro del contexto.',['Solo la traducción palabra por palabra.','La frecuencia aislada sin contexto.','La forma de la palabra sin leer la frase.'])};}
}
function renderQuestion(q){if(!q)return '<div class="card"><h2>Ejercicio no disponible</h2><p class="muted">Esta sesión necesita contenido adicional.</p></div>';
 if(q.kind==='production')return `<div class="card"><span class="eyebrow">3 · Producción</span><h2>${esc(q.instruction)}</h2><p class="muted">Intenta recuperar la forma antes de mirar la solución.</p><div class="production-result"><div class="roman">Significado</div><h2>${esc(q.prompt)}</h2><input id="prodInput" class="he-input" dir="rtl" autocomplete="off" placeholder="Escribe en hebreo"><div id="prodFeedback" class="feedback"></div>${lesson.revealed?`<div class="notice"><div class="he">${esc(q.correct)}</div><b>${esc(q.prompt)}</b><br>Pronunciación: ${esc(q.translit)}</div>`:''}<div class="lesson-actions"><button class="secondary" id="checkProd">Comprobar</button>${!lesson.revealed?'<button class="ghost-dark" id="revealProd">Ver respuesta</button>':''}</div></div></div>`;
 const label=q.kind==='recognition'?'2 · Reconocimiento':q.kind==='grammar'?'4 · Gramática en contexto':'1 · Comprensión';
 return `<div class="card"><span class="eyebrow">${label}</span><h2>${esc(q.instruction)}</h2>${q.he?`<div class="he">${esc(q.he)}</div>`:''}${q.prompt&&q.kind==='grammar'?`<div class="notice"><b>${esc(q.prompt)}</b></div>`:''}<div class="choice-list" id="choices">${(q.options||[]).map((o,i)=>`<button class="choice" data-choice="${i}">${esc(o)}</button>`).join('')}</div><div id="qFeedback" class="feedback"></div></div>`}
function renderLesson(){const s=sessionForDay(lesson.day),u=unitForDay(lesson.day);if(!s||!u){$('#lessonArea').innerHTML='<div class="card"><h2>Contenido en construcción</h2><p class="muted">Los bloques posteriores se integrarán después del Bloque 1.</p></div>';return}introduce(s.targetVocab||[]);const p=linkedPhrase(s),g=currentGrammar(s,u);lesson.question=buildQuestion(lesson.step,s,u);const done=lesson.answered;let html=`<div class="lesson-connection"><div><span class="eyebrow">Enfoque de hoy</span><b>${esc(s.title)}</b></div><div><span class="eyebrow">Palabras nuevas</span><b>${(s.targetVocab||[]).length}</b></div><div><span class="eyebrow">Repaso</span><b>${(s.reviewVocab||[]).length}</b></div><div class="family"><span class="eyebrow">Unidad</span><b>${esc(u.id+' · '+u.title)}</b>${p?`<div class="mini-he he">${esc(p.text)}</div>`:''}</div></div>`;
 html+=renderQuestion(lesson.question);
 if(done){html+=`<div class="notice">${lesson.step===2?'Respuesta comprobada. Ya puedes ver la forma, significado y pronunciación antes de avanzar.':'Respuesta comprobada. El ejercicio queda registrado como acierto.'}</div>`}
 const stepNames=['Comprensión','Reconocimiento','Producción','Gramática'];html+=`<div class="card"><div class="lesson-nav"><button class="secondary" id="prevStep" ${lesson.step===0?'disabled':''}>← Anterior</button><button class="secondary" id="nextStep" ${!done?'disabled':''}>Siguiente →</button></div><p class="eyebrow" style="text-align:center;width:100%;margin-top:12px">${esc(stepNames[lesson.step])} · ${lesson.step+1}/4</p></div>`;$('#lessonArea').innerHTML=html;wireQuestion(lesson.question,s,u)}
function wireQuestion(q,s,u){if(!q)return;
 if(q.kind==='production'){const input=$('#prodInput');$('#checkProd').onclick=()=>{const ok=norm(input.value)===norm(q.correct);lesson.answered=true;lesson.revealed=ok;recordExercise('produccion',ok,q);const f=$('#prodFeedback');f.textContent=ok?'✓ Correcto.':'✗ Todavía no. Revisa la forma mostrada y vuelve a intentarlo.';f.style.color=ok?'var(--good)':'var(--bad)';if(ok){introduce(s.targetVocab||[]);save().then(renderLesson)}else{renderLesson()}};const r=$('#revealProd');if(r)r.onclick=()=>{lesson.revealed=true;lesson.answered=true;renderLesson()};return}
 $$('#choices .choice').forEach(b=>b.onclick=()=>{const idx=Number(b.dataset.choice),selected=q.options[idx],ok=selected===q.correct;$$('#choices .choice').forEach(x=>x.disabled=true);b.classList.add(ok?'good':'bad');if(!ok){$$('#choices .choice').find(x=>x.textContent===q.correct)?.classList.add('good')}$('#qFeedback').textContent=ok?'✓ Correcto.':'✗ No es esa. La respuesta correcta queda marcada.';$('#qFeedback').style.color=ok?'var(--good)':'var(--bad)';lesson.answered=true;recordExercise(q.kind,ok,q);save().then(renderLesson)});
}
function recordExercise(kind,ok,q){state.exerciseHistory.push({ts:Date.now(),day:lesson.day,step:lesson.step,kind,correct:ok,answer:q.correct});if(state.exerciseHistory.length>2000)state.exerciseHistory=state.exerciseHistory.slice(-2000);const key=kind==='comprehension'?'comprension':kind==='recognition'?'lectura':kind==='production'?'produccion':'gramatica';state.skills[key]=Math.min(100,(state.skills[key]||0)+(ok?2:0));touch();state.sessions++}
function renderCourse(){const day=Math.min(180,Math.max(1,Number(state.day)||1));$('#dayInput').value=day;const s=sessionForDay(day),u=unitForDay(day);if(!s){$('#courseTitle').textContent=`Día ${day}`;$('#courseObjective').textContent='Este día todavía no tiene contenido definitivo.';$('#courseUnitMeta').textContent='Ruta de 180 días';$('#lessonArea').innerHTML='<div class="card"><h2>Contenido en construcción</h2><p class="muted">El motor está preparado para los bloques siguientes, pero no se publicarán ejercicios vacíos.</p></div>';return}$('#courseTitle').textContent=`Día ${day} · ${s.title}`;$('#courseObjective').textContent=s.objective;$('#courseUnitMeta').textContent=`Bloque ${u.block} · ${u.title}`;$('#courseMeta').innerHTML=`<span>Unidad ${u.id}</span><span>Sesión ${s.id}</span><span>${(s.targetVocab||[]).length} palabras nuevas hoy</span>`;if(lesson.day!==day)lesson={day,step:0,question:null,answered:false,revealed:false};renderLesson()}
function nextStep(){if(!lesson.answered)return;if(lesson.step<3){lesson.step++;lesson.answered=false;lesson.revealed=false;renderLesson()}else{completeDay()}}
async function completeDay(){if(!state.completedDays.includes(lesson.day))state.completedDays.push(lesson.day);touch();await save();if(lesson.day<180){state.day=lesson.day+1;lesson={day:state.day,step:0,question:null,answered:false,revealed:false};await save();}renderCourse()}
function routeWord(id){const v=vocab(id);if(!v)return;const c=state.cards[id];const phrases=D.phrases.filter(p=>p.tokens.some(t=>(t.vocabId||'')===id));$('#routeCard').innerHTML=`<div class="card"><span class="eyebrow">Ruta de aprendizaje · ${esc(id)}</span><div class="he">${esc(v.form)}</div><h2>${esc(v.meaning)}</h2><p><b>Lema:</b> ${esc(v.lemma||'—')} · <b>Categoría:</b> ${esc(v.category||'—')}</p>${v.gender?`<p><b>Género:</b> ${esc(v.gender)} · <b>Número:</b> ${esc(v.number||'')}</p>`:''}<p><b>Raíz:</b> ${v.root?esc(v.root):'no se presenta en esta unidad'}</p><p><b>Familia:</b> ${esc(v.family||'—')}</p><p><b>Unidades:</b> ${D.units.filter(u=>(u.newVocab||[]).includes(id)||(u.reviewVocab||[]).includes(id)).map(u=>esc(u.id+' '+u.title)).join(', ')||'—'}</p><h3>Frases</h3>${phrases.map(p=>`<div class="grammar-example"><div class="he">${esc(p.text)}</div><b>${esc(p.translation)}</b></div>`).join('')||'<p class="muted">Todavía no hay frase enlazada.</p>'}<p><b>SRS:</b> ${c?`${c.state}, ${c.reps} repasos, ${c.errors} errores`:'aún no introducida'}</p></div>`;show('stats')}
function schedule(id,r){const c=card(id),now=Date.now();c.last=now;c.reps++;if(r===0){c.errors++;c.ease=Math.max(1.3,c.ease-.2);c.interval=.04;c.state='learning'}else{const mult=[.55,1.15,2.5,3.4][r];c.interval=Math.max(.04,c.interval?c.interval*mult*(c.ease/2.5):[.007,.04,1,3][r]);c.ease=Math.max(1.3,c.ease+[-.18,-.05,.03,.12][r]);c.state=c.interval>=1?'review':'learning'}c.due=now+c.interval*86400000;state.history.push({ts:now,id,rating:r,interval:c.interval});if(state.history.length>1500)state.history=state.history.slice(-1500);touch()}
function renderReview(){const q=due().sort((a,b)=>score(b)-score(a)).slice(0,25);review.queue=q;review.cursor=Math.min(Math.max(0,review.cursor),Math.max(0,q.length-1));if(!q.length){$('#reviewCount').textContent='0';$('#reviewCard').innerHTML='<h2>Todo al día</h2><p class="muted">Las nuevas tarjetas entran desde el Curso o desde el Lector.</p>';return}const v=q[review.cursor],c=card(v.id),rated=review.ratings[v.id]!==undefined;$('#reviewCount').textContent=q.length;$('#reviewCard').innerHTML=`<div class="eyebrow">Tarjeta ${review.cursor+1} de ${q.length}</div><div class="he">${esc(v.form)}</div><div class="roman">${esc(v.translit||'')}</div><p id="rm" class="meaning ${rated?'':'hidden'}">${esc(v.meaning)}</p><div class="review-actions"><button class="secondary" id="rprev" ${review.cursor===0?'disabled':''}>← Anterior</button><button class="secondary" id="reveal">${rated?'Ver significado':'Revelar'}</button>${rated&&review.cursor<q.length-1?'<button class="primary" id="rnext">Siguiente →</button>':''}</div>${rated?'<div class="notice">Ya calificada. Puedes volver atrás sin generar otra calificación.</div>':`<div id="ratings" class="review-actions"><button class="danger" data-r="0">Otra vez</button><button class="secondary" data-r="1">Difícil</button><button class="secondary" data-r="2">Bien</button><button class="primary" data-r="3">Fácil</button></div>`}<p class="muted small">Repasos: ${c.reps} · Errores: ${c.errors}</p>`;$('#reveal').onclick=()=>$('#rm').classList.remove('hidden');$('#rprev').onclick=()=>{if(review.cursor>0){review.cursor--;renderReview()}};const rn=$('#rnext');if(rn)rn.onclick=()=>{review.cursor++;renderReview()};$$('[data-r]').forEach(b=>b.onclick=()=>{const r=Number(b.dataset.r);schedule(v.id,r);review.ratings[v.id]=r;state.sessions++;save().then(renderReview)})}
function renderReader(){const level=Math.min(5,Math.max(1,Math.ceil(state.day/36))),texts=(D.reader||[]).filter(t=>t.level===level);$('#readerLevels').innerHTML=[1,2,3,4,5].map(x=>`<span class="${x<=level?'':'muted'}">Nivel ${x}</span>`).join('');const t=texts[(state.day-1)%Math.max(1,texts.length)]||D.reader?.[0];if(!t){$('#readerText').innerHTML='<div class="card">No hay lecturas.</div>';return}$('#readerText').innerHTML=`<article class="card"><span class="eyebrow">${esc(t.reference||'')}</span><h2>${esc(t.title)}</h2><div class="reader-he">${(t.tokens||[]).map(tok=>`<button class="token" data-reader-word="${esc(tok.vocab_id||'')}">${esc(tok.text)}</button>`).join(' ')}</div><p>${esc(t.translation||'')}</p><p class="muted">${esc(t.question||'')}</p><button class="secondary" id="readerSrs">Enviar palabras conocidas al SRS</button></article>`;$$('[data-reader-word]').forEach(b=>b.onclick=()=>{const v=vocab(b.dataset.readerWord);if(v)routeWord(v.id)});$('#readerSrs').onclick=async()=>{(t.tokens||[]).map(x=>x.vocab_id).filter(id=>vocab(id)).forEach(id=>card(id));await save();alert('Palabras añadidas al SRS.')}}
function renderAlphabet(){const finals={כ:'ך',מ:'ם',נ:'ן',פ:'ף',צ:'ץ'};$('#letterGrid').innerHTML=D.alphabet.map(a=>`<div class="letter"><div class="he">${esc(a.char)}</div><b>${esc(a.name)}</b><div class="muted small">${esc(a.sound)}</div>${finals[a.char]?`<div class="final-form"><span class="he">${a.char}</span><span>→</span><span class="he">${finals[a.char]}</span></div>`:''}</div>`).join('');$('#vocalGrid').innerHTML=D.vocal.map(x=>`<div class="card vocal"><div class="he">${esc(x.mark||x.symbol||'')}</div><h3>${esc(x.name)}</h3><p>${esc(x.approx||x.sound||'')}</p><div class="muted small">${esc(x.example||'')}</div></div>`).join('')}
function renderGrammar(){$('#grammarGrid').innerHTML=D.grammar.map(g=>`<article class="card grammar-card"><span class="eyebrow">Referencia</span><h2>${esc(g.title)}</h2><p>${esc(g.summary)}</p><div class="he">${esc(g.example)}</div><p><b>${esc(g.translation)}</b></p><details><summary>Explicación</summary><p>${esc(g.note)}</p>${(g.examples||[]).map(e=>`<div class="grammar-example"><div class="he">${esc(e.hebrew)}</div><b>${esc(e.meaning)}</b><div class="muted small">${esc(e.analysis)}</div></div>`).join('')}</details></article>`).join('')}
function renderStats(){const hist=state.exerciseHistory||[],correct=hist.filter(x=>x.correct).length;$('#stSessions').textContent=state.sessions;$('#stAccuracy').textContent=hist.length?Math.round(correct/hist.length*100)+'%':'0%';$('#stMastered').textContent=Object.values(state.cards).filter(c=>c.state==='review'&&c.interval>=21).length;$('#stReviews').textContent=state.history.length;$('#skillBars').innerHTML=Object.entries(state.skills).map(([k,v])=>`<p><b>${esc(k)}</b></p><div class="progress"><i style="width:${Math.min(100,v)}%"></i></div>`).join('');$('#activityText').textContent=`${state.activeDays.length} días activos · ${state.completedDays.length} sesiones completadas.`}
function renderProfilePanel(){metaGet('profiles').then(p=>$('#profilePanel').innerHTML=`<div class="card profile-box"><span class="eyebrow">Perfil local</span><h2>${esc(profileName)}</h2><p class="muted small">Cada perfil mantiene su progreso por separado.</p><select id="profileSelect">${p.map(x=>`<option value="${x.id}" ${x.id===profileId?'selected':''}>${esc(x.name)}</option>`).join('')}</select><div class="row"><input id="newProfileName" maxlength="28" placeholder="Nuevo usuario"><button class="secondary" id="createProfile">Crear</button></div><button class="secondary" id="resetProfile">Restablecer progreso</button></div>`).then(()=>{$('#profileSelect').onchange=async e=>{profileId=e.target.value;await metaPut('activeProfile',profileId);await initProfiles();show('home')};$('#createProfile').onclick=async()=>{const n=$('#newProfileName').value.trim();if(!n)return;const p=await metaGet('profiles')||[];if(p.some(x=>x.name.toLowerCase()===n.toLowerCase()))return alert('Ese perfil ya existe.');const x={id:'p_'+Date.now(),name:n,createdAt:Date.now()};p.push(x);await metaPut('profiles',p);await metaPut('activeProfile',x.id);await initProfiles();show('home')};$('#resetProfile').onclick=async()=>{if(confirm('¿Restablecer este perfil?')){state=structuredClone(DEFAULT);await save();show('home')}}})}
function setup(){document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)show(b.dataset.view)});$('#goDay').onclick=()=>{const d=Math.min(180,Math.max(1,Number($('#dayInput').value)||1));state.day=d;lesson={day:d,step:0,question:null,answered:false,revealed:false};show('course')};$('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({app:'Mikhael',version:'5.1',profile:{id:profileId,name:profileName},state},null,2)],{type:'application/json'}));a.download='mikhael-progreso-v5.1.json';a.click()};$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{const r=new FileReader();r.onload=async()=>{try{const x=JSON.parse(r.result);state={...structuredClone(DEFAULT),...x.state,skills:{...DEFAULT.skills,...x.state.skills},settings:{...DEFAULT.settings,...x.state.settings},exerciseHistory:x.state.exerciseHistory||[]};await save();alert('Progreso importado.')}catch(err){alert('No se pudo importar: '+err.message)}};r.readAsText(e.target.files[0])};$('#storageInfo').onclick=()=>navigator.storage?.persist?.().then(ok=>alert(ok?'Almacenamiento persistente solicitado.':'El navegador no confirmó persistencia.'));['largeText','reduceMotion','haptic'].forEach(id=>$('#'+id).onchange=e=>{state.settings[id]=e.target.checked;document.body.classList.toggle(id==='largeText'?'large-he':'reduce-motion',e.target.checked);save()});document.addEventListener('click',e=>{if(e.target.closest('#nextStep'))nextStep();if(e.target.closest('#prevStep')&&lesson.step>0){lesson.step--;lesson.answered=false;lesson.revealed=false;renderLesson()}});renderProfilePanel()}
(async()=>{try{await load();await initProfiles();setup();show('home');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});}catch(e){document.body.innerHTML=`<main class="wrap"><div class="card"><h1>Error al cargar Mikhael v5.1</h1><p>${esc(e.message)}</p></div></main>`}})();
