const DB_NAME='hebreo-vivo-v4', DB_VER=4, STORE='profiles';
const META='meta';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DEFAULT={day:1,completedDays:[],sessions:0,activeDays:[],streak:0,lastActive:null,skills:{comprension:0,escucha:0,lectura:0,produccion:0,gramatica:0},cards:{},history:[],settings:{largeText:false,reduceMotion:false,haptic:true},readerDone:{},readerStats:{},courseStartedAt:null};
let DATA={alphabet:[],vocab:[],phrases:[],grammar:[],course:[],reader:[],vocalization:[],plans:[],morphology:[]};
let state=structuredClone(DEFAULT); let currentProfileId=null; let currentProfileName=''; let currentView='home'; let lesson=null;
let review={queue:[],cursor:0,ratings:{},path:[]}; let deferredInstall=null;

async function loadData(){
 const files=['alphabet','vocabulary','phrases','grammar','course','reader','vocalization','lesson-plans','morphology'];
 const vals=await Promise.all(files.map(f=>fetch(`./data/${f}.json`).then(r=>{if(!r.ok)throw Error(f);return r.json()})));
 files.forEach((f,i)=>{const k=f==='vocabulary'?'vocab':f==='lesson-plans'?'plans':f;DATA[k]=vals[i]});
}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VER);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE);if(!db.objectStoreNames.contains(META))db.createObjectStore(META)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function metaGet(key){try{const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction(META).objectStore(META).get(key);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}catch{return null}}
async function metaPut(key,val){const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction(META,'readwrite').objectStore(META).put(val,key);q.onsuccess=res;q.onerror=()=>rej(q.error)})}
async function dbGet(){if(!currentProfileId)return null;try{const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction(STORE).objectStore(STORE).get(currentProfileId);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)})}catch{return null}}
async function dbPut(){const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).put(state,currentProfileId);q.onsuccess=res;q.onerror=()=>rej(q.error)})}
async function profiles(){return (await metaGet('profiles'))||[]}
async function saveProfiles(p){await metaPut('profiles',p)}
async function ensureProfile(){let p=await profiles();let active=await metaGet('activeProfile');if(!p.length){const id='p_'+Date.now();p=[{id,name:'Mi perfil',createdAt:Date.now()}];active=id;await saveProfiles(p);await metaPut('activeProfile',active)}currentProfileId=active||p[0].id;const x=p.find(x=>x.id===currentProfileId)||p[0];currentProfileId=x.id;currentProfileName=x.name}
async function switchProfile(id){const p=await profiles(),x=p.find(x=>x.id===id);if(!x)return;currentProfileId=id;currentProfileName=x.name;await metaPut('activeProfile',id);const old=await dbGet();state=old?{...structuredClone(DEFAULT),...old,skills:{...DEFAULT.skills,...old.skills},settings:{...DEFAULT.settings,...old.settings}}:structuredClone(DEFAULT);lesson=null;review={queue:[],cursor:0,ratings:{},path:[]};applySettings();renderProfilePanel();show('home')}
async function createProfile(name){name=(name||'').trim().slice(0,28);if(!name){alert('Escribe un nombre para el perfil.');return}const p=await profiles();if(p.some(x=>x.name.toLowerCase()===name.toLowerCase())){alert('Ya existe un perfil con ese nombre.');return}const x={id:'p_'+Date.now(),name,createdAt:Date.now()};p.push(x);await saveProfiles(p);await metaPut('activeProfile',x.id);currentProfileId=x.id;currentProfileName=x.name;state=structuredClone(DEFAULT);await dbPut();renderProfilePanel();show('home')}
async function resetCurrentProfile(){if(!confirm(`¿Restablecer por completo el progreso de ${currentProfileName}? Esta acción no se puede deshacer.`))return;state=structuredClone(DEFAULT);lesson=null;review={queue:[],cursor:0,ratings:{},path:[]};await save();show('home')}
async function deleteCurrentProfile(){const p=await profiles();if(p.length<=1){alert('Debe existir al menos un perfil. Puedes restablecer este perfil en su lugar.');return}if(!confirm(`¿Eliminar el perfil ${currentProfileName} y todo su progreso local?`))return;const db=await openDB();await new Promise((res,rej)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).delete(currentProfileId);q.onsuccess=res;q.onerror=()=>rej(q.error)});const rest=p.filter(x=>x.id!==currentProfileId);await saveProfiles(rest);await metaPut('activeProfile',rest[0].id);await switchProfile(rest[0].id)}
function renderProfilePanel(){const host=$('#profilePanel');if(!host)return;profiles().then(p=>{host.innerHTML=`<div class="profile-box"><span class="eyebrow">Perfil local</span><h2>${currentProfileName||'Mi perfil'}</h2><p class="muted small">Cada perfil guarda por separado su curso, SRS, estadísticas y lecturas. No se requiere correo electrónico.</p><select id="profileSelect">${p.map(x=>`<option value="${x.id}" ${x.id===currentProfileId?'selected':''}>${x.name}</option>`).join('')}</select><div class="row"><input id="newProfileName" maxlength="28" placeholder="Nuevo usuario"><button class="secondary" id="createProfileBtn">Crear</button></div><div class="row"><button class="secondary" id="resetProfileBtn">Restablecer este perfil</button><button class="danger" id="deleteProfileBtn">Eliminar perfil</button></div></div>`;$('#profileSelect').onchange=e=>switchProfile(e.target.value);$('#createProfileBtn').onclick=()=>createProfile($('#newProfileName').value);$('#resetProfileBtn').onclick=resetCurrentProfile;$('#deleteProfileBtn').onclick=deleteCurrentProfile})}
function applySettings(){document.body.classList.toggle('large-he',state.settings.largeText);document.body.classList.toggle('reduce-motion',state.settings.reduceMotion);if($('#largeText')){$('#largeText').checked=state.settings.largeText;$('#reduceMotion').checked=state.settings.reduceMotion;$('#haptic').checked=state.settings.haptic}}
async function save(){await dbPut();renderGlobal()}
function today(){return new Date().toISOString().slice(0,10)}
function touchActivity(){const d=today();if(!state.activeDays.includes(d))state.activeDays.push(d);if(state.lastActive!==d){const y=new Date();y.setDate(y.getDate()-1);const yd=y.toISOString().slice(0,10);state.streak=state.lastActive===yd?state.streak+1:1;state.lastActive=d}}
function normalize(s){return s.normalize('NFD').replace(/[\u0591-\u05C7]/g,'').replace(/\s+/g,'').trim().toLowerCase()}
function speak(t,rate=.78){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='he-IL';u.rate=rate;speechSynthesis.speak(u)}
function vibrate(ms=12){if(state.settings.haptic&&navigator.vibrate)navigator.vibrate(ms)}
function cardState(id){return state.cards[id]||(state.cards[id]={id,created:Date.now(),last:null,due:Date.now(),interval:0,ease:2.5,reps:0,errors:0,state:'new'})}
function scoreCard(v){const c=state.cards[v.id];if(!c)return 100000;const overdue=Math.max(0,Date.now()-(c.due||0))/3600000;return overdue*5+c.errors*18+(2.5-(c.ease||2.5))*15-(c.reps||0)*.25}
function activeVocab(){return DATA.vocab.filter(v=>!v.deprecated)}
function dueCards(){const now=Date.now();return activeVocab().filter(v=>{const c=state.cards[v.id];return !c||!c.due||c.due<=now})}
function adaptiveQueue(limit=25){return [...activeVocab()].sort((a,b)=>scoreCard(b)-scoreCard(a)).slice(0,limit)}
function schedule(id,rating){
 const c=cardState(id),now=Date.now(); c.last=now; c.reps++;
 if(rating===0){ c.errors++; c.ease=Math.max(1.3,c.ease-.2); c.state='learning'; c.interval=c.reps<=2?.007:.04; }
 else if(c.state==='new'||c.state==='learning'){
   const steps=[.007,.04,1,3]; const step=Math.min(3,Math.max(0,c.learningStep||0)+(rating>=2?1:-1));
   c.learningStep=step; c.interval=steps[step]; c.state=step>=2?'review':'learning';
   c.ease=Math.max(1.3,c.ease+[-.12,-.04,.02,.12][rating]);
 } else {
   const mult=[.55,1.15,2.5,3.4][rating]; c.interval=Math.max(1,c.interval*mult*(c.ease/2.5));
   c.ease=Math.max(1.3,c.ease+[-.18,-.05,.03,.12][rating]); c.state='review';
 }
 c.due=now+c.interval*86400000; state.history.push({ts:now,id,rating,interval:c.interval,ease:c.ease});
 if(state.history.length>1500)state.history=state.history.slice(-1500);
 touchActivity();
}
function formatInterval(days){if(days<1)return Math.max(1,Math.round(days*24))+' h';if(days<30)return Math.round(days)+' d';return Math.round(days/30)+' mes'}
function show(view){currentView=view;$$('.view').forEach(x=>x.classList.toggle('hidden',x.id!==view));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='course')renderCourse();if(view==='review')renderReview();if(view==='reader')renderReader();if(view==='alphabet')renderAlphabet();if(view==='grammar')renderGrammar();if(view==='stats')renderStats();renderGlobal();scrollTo({top:0,behavior:'auto'})}
function renderGlobal(){const pn=$('#profileName');if(pn)pn.textContent=currentProfileName;const due=dueCards().length,pct=Math.round(state.completedDays.length/180*100);$('#dueBadge').textContent=due;$('#mobileDue').textContent=due;$('#homeDay').textContent=state.day;$('#homeDue').textContent=due;$('#homeDueInline').textContent=due;$('#homeStreak').textContent=state.streak;$('#homeGoal').textContent=DATA.plans[state.day-1]?.objective||'';$('#dayProgress').style.width=pct+'%';$('#sessionSummary').textContent=`${state.completedDays.length} de 180 días completados · ${pct}% de la ruta.`;$('#knownCount').textContent=Object.values(state.cards).filter(c=>c.state==='review'&&c.interval>=21).length;const weak=adaptiveQueue(1)[0];$('#adaptiveAdvice').textContent=due?`Tienes ${due} tarjetas pendientes. El sistema priorizará las que más necesitan recuperación.`:(weak?`No hay vencidas. Puedes adelantar una unidad débil: ${weak.hebrew} · ${weak.meaning}.`:'Empieza la lección de hoy.')}
function planForDay(){return DATA.plans[Math.min(179,Math.max(0,state.day-1))]||DATA.plans[0]}
function unitsForPlan(plan){const base=plan.unit_ids.map(id=>DATA.vocab.find(v=>v.id===id)).filter(Boolean);const weak=adaptiveQueue(6);return [...new Map([...base,...weak].map(v=>[v.id,v])).values()].slice(0,6)}
function startLesson(){const p=planForDay(), units=unitsForPlan(p), phrase=DATA.phrases[(state.day-1)%DATA.phrases.length]||DATA.reader[0];lesson={plan:p,units,phrase,index:0,steps:[]};renderLessonStep()}
function renderCourse(){const p=planForDay();$('#courseTitle').textContent=p.title;$('#courseObjective').textContent=p.objective;$('#courseMeta').innerHTML=`<span>Fase ${p.phase}</span><span>${p.minutes} min</span><span>Enfoque: ${p.focus}</span>`;$('#dayInput').value=state.day;if(!lesson||lesson.plan.day!==p.day)startLesson()}
function renderLessonStep(){const box=$('#lessonArea'),u=lesson.units[lesson.index%lesson.units.length],p=lesson.phrase;const step=lesson.index;
 if(step===0){box.innerHTML=`<div class="card lesson"><div class="eyebrow">1 · Comprensión + escucha</div><div class="he">${p.hebrew}</div><div class="roman">${p.translit||''}</div><div class="meaning">${p.meaning||''}</div><div class="lesson-actions"><button class="secondary" id="hear">🔊 Escuchar</button><button class="primary" id="next">Entendido →</button></div><p class="feedback muted">Escucha primero. Intenta captar la idea general antes de analizar cada palabra.</p></div>`;$('#hear').onclick=()=>speak(p.hebrew);$('#next').onclick=()=>{state.skills.comprension+=1;lesson.index++;renderLessonStep()};return}
 if(step===1){const opts=[u,...DATA.vocab.filter(x=>x.id!==u.id).sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5);box.innerHTML=`<div class="card lesson"><div class="eyebrow">2 · Reconocimiento</div><div class="he">${u.hebrew}</div><p>¿Qué significa?</p><div class="choice-list">${opts.map(o=>`<button class="choice" data-id="${o.id}">${o.meaning}</button>`).join('')}</div><p id="fb" class="feedback"></p></div>`;$$('.choice').forEach(b=>b.onclick=()=>{const ok=b.dataset.id===u.id;$('#fb').textContent=ok?'✓ Correcto. Recuperaste la unidad.':'No esta vez. Observa la forma y vuelve a intentarlo en otra tarjeta.';b.classList.add(ok?'good':'bad');$$('.choice').forEach(x=>x.disabled=true);schedule(u.id,ok?2:0);state.skills.comprension+=ok?1:0;touchActivity();vibrate(ok?10:30);setTimeout(()=>{lesson.index++;save();renderLessonStep()},450)});return}
 if(step===2){box.innerHTML=`<div class="card lesson"><div class="eyebrow">3 · Lectura + producción</div><div class="meaning">Escribe en hebreo:</div><div class="he small-he">${u.hebrew}</div><input id="prod" dir="rtl" class="he-input" placeholder="Escribe aquí…" autocomplete="off"><div class="lesson-actions"><button class="secondary" id="hear">🔊 Escuchar</button><button class="primary" id="check">Comprobar</button></div><p id="pf" class="feedback"></p></div>`;$('#hear').onclick=()=>speak(u.hebrew);$('#check').onclick=()=>{const ok=normalize($('#prod').value)===normalize(u.hebrew);$('#pf').textContent=ok?'✓ Muy bien.':'Aún no. Mira el modelo, escucha y vuelve a intentarlo.';if(ok){state.skills.produccion+=2;state.skills.lectura+=1;vibrate(10);setTimeout(()=>{lesson.index++;renderLessonStep()},500)}else{state.skills.produccion=Math.max(0,state.skills.produccion-0);vibrate(30)}};return}
 if(step===3){const g=DATA.grammar[(state.day-1)%DATA.grammar.length];box.innerHTML=`<div class="card lesson grammar-mini"><div class="eyebrow">4 · Gramática en contexto</div><h2>${g.title}</h2><p>${g.summary}</p><div class="he">${g.example}</div><p><b>${g.translation}</b></p><details><summary>¿Por qué?</summary><p>${g.note}</p>${(g.examples||[]).slice(0,2).map(e=>`<div class="grammar-example"><div class="he">${e.hebrew}</div><b>${e.meaning}</b><div class="muted small">${e.analysis}</div></div>`).join('')}</details><button class="primary wide" id="finishLesson">Completar sesión</button></div>`;$('#finishLesson').onclick=completeDay;return}
}
async function completeDay(){
 const day=state.day; if(!state.completedDays.includes(day))state.completedDays.push(day);
 const r=readerRecommendedText(); if(r)state.readerDone[r.id]=(state.readerDone[r.id]||0)+1;
 state.day=Math.min(180,state.day+1); state.sessions++; touchActivity(); state.skills.comprension+=1; state.skills.lectura+=1;
 if(!state.courseStartedAt)state.courseStartedAt=Date.now(); await save(); lesson=null; renderCourse(); show('home');
}
function beginReview(){if(review.queue.length)return;const due=dueCards().sort((a,b)=>scoreCard(b)-scoreCard(a));const newCards=activeVocab().filter(v=>!state.cards[v.id]);const pool=[...due,...newCards.filter(v=>!due.some(d=>d.id===v.id))];review.queue=pool.slice(0,25);review.cursor=0;review.ratings={};review.path=[0]}
function currentReview(){return review.queue[review.cursor]}
function renderReview(){beginReview();const q=review.queue;if(!q.length){$('#reviewCount').textContent='0';$('#reviewCard').innerHTML='<div class="eyebrow">Todo al día</div><h2>No hay tarjetas pendientes.</h2><p class="muted">Vuelve cuando llegue la próxima revisión.</p>';return}const v=currentReview(),c=cardState(v.id),rated=review.ratings[v.id]!==undefined;$('#reviewCount').textContent=q.filter(x=>review.ratings[x.id]===undefined).length;$('#reviewCard').innerHTML=`<div class="eyebrow">Tarjeta ${review.cursor+1} de ${q.length}</div><div class="he">${v.hebrew}</div><div class="roman">${v.translit||''}</div><p id="meaning" class="meaning ${rated?'':'hidden'}">${v.meaning}</p><button class="secondary" id="hear">🔊 Escuchar</button><div class="review-actions"><button class="secondary" id="prev" ${review.cursor===0?'disabled':''}>← Anterior</button><button class="secondary" id="reveal">${rated?'Ver significado':'Revelar'}</button></div><div id="ratings" class="review-actions ${rated?'hidden':''}"><button class="danger" data-r="0">Otra vez</button><button class="secondary" data-r="1">Difícil</button><button class="secondary" data-r="2">Bien</button><button class="primary" data-r="3">Fácil</button></div>${rated?'<div class="notice"><b>Ya calificada.</b> Puedes volver a verla con «Anterior» sin generar otro repaso.</div>':''}<p class="muted small">Repasos: ${c.reps} · Errores: ${c.errors} · Intervalo: ${formatInterval(c.interval)}</p>`;$('#hear').onclick=()=>speak(v.hebrew);$('#reveal').onclick=()=>$('#meaning').classList.remove('hidden');$('#prev').onclick=()=>{if(review.cursor>0){review.cursor--;renderReview()}};$$('#ratings [data-r]').forEach(b=>b.onclick=()=>gradeReview(Number(b.dataset.r)))}
async function gradeReview(r){const v=currentReview();if(review.ratings[v.id]!==undefined)return;schedule(v.id,r);review.ratings[v.id]=r;state.sessions++;touchActivity();state.skills.escucha+=r>=2?1:0;if(r===0)state.skills.comprension=Math.max(0,state.skills.comprension-0);vibrate(r===0?30:10);if(review.cursor<review.queue.length-1)review.cursor++;else review.cursor=review.queue.findIndex(x=>review.ratings[x.id]===undefined);if(review.cursor<0)review.cursor=0;await save();renderReview()}
function stripHebrew(s=''){return String(s).normalize('NFD').replace(/[\u0591-\u05C7]/g,'').replace(/[־׃׀,.;:!?()\[\]{}]/g,'').replace(/\s+/g,'').trim().toLowerCase()}
function vocabForToken(tok){if(tok.vocab_id){const byId=DATA.vocab.find(x=>x.id===tok.vocab_id);if(byId)return byId}const key=stripHebrew(tok.text);return activeVocab().find(x=>stripHebrew(x.hebrew)===key)||null}
function morphForToken(tok){const key=stripHebrew(tok.text);return DATA.morphology.find(x=>stripHebrew(x.surface)===key)||null}
function tokenParts(text){return String(text).split('־').map(x=>x.trim()).filter(Boolean)}
function readerUnlockLevel(){return Math.min(5,Math.max(1,Math.ceil((state.day||1)/36)))}
function readerRecommendedText(){const unlocked=readerUnlockLevel();const exact=DATA.reader.filter(t=>t.level===unlocked);return exact[(state.day-1)%Math.max(1,exact.length)]||DATA.reader.find(t=>t.level===unlocked)||DATA.reader[0]}
function readerOpenText(id){return DATA.reader.find(t=>t.id===id)||readerRecommendedText()}
function readerTokenCount(t){return (t.tokens||[]).length}
function renderReader(){
 const unlocked=readerUnlockLevel();
 const labels={1:'inicio',2:'básico',3:'guiado',4:'intermedio',5:'independiente'};
 $('#readerLevels').innerHTML=[1,2,3,4,5].map(l=>{const locked=l>unlocked;return `<button class="secondary ${currentReaderLevel===l?'active':''}" data-level="${l}" ${locked?'disabled':''}>Nivel ${l}${locked?' · 🔒':''}</button>`}).join('');
 $$('#readerLevels [data-level]').forEach(b=>b.onclick=()=>{currentReaderLevel=Number(b.dataset.level);selectedReaderTextId=null;renderReader()});
 const texts=DATA.reader.filter(t=>t.level===currentReaderLevel).sort((a,b)=>(a.order||0)-(b.order||0));
 const recommended=readerRecommendedText();
 if(!selectedReaderTextId || !texts.some(t=>t.id===selectedReaderTextId))selectedReaderTextId=(recommended.level===currentReaderLevel?recommended.id:texts[0]?.id);
 const t=readerOpenText(selectedReaderTextId); if(!t){$('#readerText').innerHTML='<div class="card"><h2>No hay lecturas disponibles.</h2></div>';return;}
 const tokens=t.tokens||[]; const newCount=tokens.filter(tok=>{const v=vocabForToken(tok);return v&&!state.cards[v.id]}).length;
 const done=!!state.readerDone[t.id]; const stats=state.readerStats[t.id]||{opens:0,words:0,help:0};
 const morphCount=tokens.filter(tok=>morphForToken(tok)).length;
 $('#readerText').innerHTML=`<div class="card"><div class="split"><div><span class="eyebrow">Nivel ${currentReaderLevel} · ${labels[currentReaderLevel]}</span><h2>Textos disponibles</h2><p class="muted small">Desbloqueado hasta nivel ${unlocked} según tu día ${state.day}. La dificultad aumenta en longitud, morfología y autonomía.</p></div><div class="statcard"><span>Palabras nuevas</span><strong>${newCount}</strong><small>${morphCount} con análisis morfológico</small></div></div><div class="reader-list">${texts.map(x=>{const d=!!state.readerDone[x.id];return `<button class="reader-choice ${x.id===t.id?'active':''}" data-reader-id="${x.id}"><span><b>${x.title}</b><small>${x.reference} · ${readerTokenCount(x)} palabras ${d?'· ✓ leída':''}</small></span>${x.id===recommended.id&&x.level===unlocked?'<em>Recomendado</em>':''}</button>`}).join('')}</div></div>`;
 $('#readerText').insertAdjacentHTML('beforeend',`<div class="card"><span class="eyebrow">${t.reference}</span><h2>${t.title}</h2><div class="reader-meta"><span>${tokens.length} palabras</span><span>${newCount} nuevas</span><span>${morphCount} análisis</span><span>${done?'✓ completada':'pendiente'}</span></div><div class="readerline">${tokens.map((tok,i)=>`<button class="readerword" data-token-index="${i}">${tok.text}</button>`).join(' ')}</div><div class="lesson-actions"><button class="secondary" id="readerSpeak">🔊 Escuchar texto</button><button class="secondary" id="showTranslation">Ver traducción</button><button class="primary" id="finishReader">${done?'✓ Repasar lectura':'Marcar lectura como hecha'}</button></div><div id="readerTranslation" class="reader-help hidden"><b>Traducción de estudio</b><p>${t.translation}</p></div><div id="readerHelp" class="reader-help" aria-live="polite">Toca una palabra. Cuando exista ficha morfológica, verás lema, raíz, categoría y forma gramatical.</div><div class="reader-question"><b>Comprueba comprensión</b><p>${t.question}</p><details><summary>Mostrar respuesta</summary><p><b>${t.answer}</b></p></details><p class="muted small">${t.note}</p></div></div>`);
 $$('.reader-choice').forEach(b=>b.onclick=()=>{selectedReaderTextId=b.dataset.readerId;renderReader()});
 stats.opens++; state.readerStats[t.id]=stats;
 $('#readerSpeak').onclick=()=>{speak(t.hebrew);state.skills.escucha+=1;save()}; $('#showTranslation').onclick=()=>$('#readerTranslation').classList.toggle('hidden');
 $('#finishReader').onclick=async()=>{state.readerDone[t.id]=Date.now();state.skills.lectura+=2;touchActivity();await save();renderReader()};
 $$('.readerword').forEach(b=>b.onclick=()=>{
   const tok=tokens[Number(b.dataset.tokenIndex)],v=vocabForToken(tok),m=morphForToken(tok);
   $$('.readerword').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');stats.words++;
   if(!v&&!m){$('#readerHelp').innerHTML=`<b>Ayuda contextual</b><p class="muted small">Esta forma todavía no tiene una ficha completa. Intenta identificar su función por el contexto.</p>`;return;}
   if(v)stats.help++;
   const c=v?cardState(v.id):null;
   const parts=tokenParts(tok.text);
   $('#readerHelp').innerHTML=`<div class="reader-help-head"><div class="he">${tok.text}</div><div class="roman">${v?.translit||m?.lemma||''}</div></div>${v?`<h3>${v.meaning}</h3><div class="muted small">${v.category||'unidad léxica'}${v.root?' · raíz '+v.root:''}</div>${v.frequency_rank?`<div class="muted small">Frecuencia léxica: #${v.frequency_rank}</div>`:''}`:''}${m?`<div class="morph-card"><div class="eyebrow">Análisis morfológico</div><div class="morph-grid"><div><b>Lema</b><span class="he morph-he">${m.lemma}</span></div><div><b>Raíz</b><span>${m.root||'—'}</span></div><div><b>Categoría</b><span>${m.pos}</span></div><div><b>Forma</b><span>${m.morphology}</span></div></div><p><b>Sentido:</b> ${m.gloss}</p><p class="muted small">${m.note}</p></div>`:`<div class="morph-note"><b>Análisis inicial</b><br>La ficha léxica está disponible, pero todavía no hay una ficha morfológica específica para esta forma.</div>`}${parts.length>1?`<p class="muted small">Maqqef: esta unidad gráfica contiene ${parts.length} elementos; puedes estudiar sus componentes por separado cuando estén disponibles.</p>`:''}<div class="row reader-help-actions">${v?`<button class="secondary" id="rh">🔊 Escuchar</button><button class="secondary" id="add">${c.reps?'Repasar en SRS':'Añadir al SRS'}</button>`:'<button class="secondary" id="rh">🔊 Escuchar forma</button>'}</div>`;
   $('#rh').onclick=()=>speak(tok.text);
   if(v)$('#add').onclick=async()=>{cardState(v.id);await save();$('#readerHelp').insertAdjacentHTML('beforeend','<p class="feedback">✓ Esta unidad ya está en tu SRS.</p>');updateDue()};
 });
 save();
}

let currentReaderLevel=1; let selectedReaderTextId=null;
function renderAlphabet(){const finals={כ:'ך',מ:'ם',נ:'ן',פ:'ף',צ:'ץ'};$('#letterGrid').innerHTML=DATA.alphabet.map(a=>`<div class="letter"><div class="he">${a.char}</div><b>${a.name}</b><div class="muted small">${a.sound}</div>${finals[a.char]?`<div class="final-form"><span class="he">${a.char}</span><span>→</span><span class="he">${finals[a.char]}</span></div>`:''}<button class="ghost-dark wide" data-speak="${a.char}" style="margin-top:8px">🔊</button></div>`).join('');$$('[data-speak]').forEach(b=>b.onclick=()=>speak(b.dataset.speak));$('#vocalGrid').innerHTML=DATA.vocalization.map(x=>`<div class="card vocal"><div class="he">${x.symbol||x.char||''}</div><h3>${x.name||x.title||''}</h3><p>${x.sound||x.description||''}</p><div class="muted small">${x.example||''}</div></div>`).join('')}
function renderGrammar(){$('#grammarGrid').innerHTML=DATA.grammar.map(g=>`<article class="card grammar-card"><span class="eyebrow">Gramática</span><h2>${g.title}</h2><p>${g.summary}</p><div class="he">${g.example}</div><p><b>${g.translation}</b></p><details><summary>Explicación y cuándo se usa</summary><p>${g.note}</p><div class="grammar-examples">${(g.examples||[]).map(e=>`<div class="grammar-example"><div class="he">${e.hebrew}</div><b>${e.meaning}</b><div class="muted small">${e.analysis}</div></div>`).join('')}</div></details></article>`).join('')}
function renderStats(){
 const h=state.history,correct=h.filter(x=>x.rating>=2).length; $('#stSessions').textContent=state.sessions; $('#stAccuracy').textContent=(h.length?Math.round(correct/h.length*100):0)+'%'; $('#stMastered').textContent=Object.values(state.cards).filter(c=>c.state==='review'&&c.interval>=21).length; $('#stReviews').textContent=h.length;
 const names={comprension:'Comprensión',escucha:'Escucha',lectura:'Lectura',produccion:'Producción',gramatica:'Gramática'}; $('#skillBars').innerHTML=Object.entries(names).map(([k,n])=>{const v=Math.min(100,state.skills[k]||0);return `<div class="bar"><span>${n}</span><div class="progress"><i style="width:${v}%"></i></div><b>${v}</b></div>`}).join('');
 const retention=h.length?Math.round(correct/h.length*100):0; const reviewed=Object.values(state.cards).filter(c=>c.reps).length; const due=dueCards().length;
 $('#retentionText').innerHTML=`<p><strong>${retention}%</strong> de aciertos recientes.</p><p class="muted small">${reviewed} unidades ya tienen historial · ${due} pendientes ahora.</p><p class="muted small">Lecturas completadas: ${Object.keys(state.readerDone).length}/${DATA.reader.length}.</p>`;
 const weak=DATA.vocab.map(v=>({v,c:state.cards[v.id]})).filter(x=>x.c&&x.c.errors>0).sort((a,b)=>b.c.errors-a.c.errors).slice(0,8); $('#weakList').innerHTML=weak.length?weak.map(x=>`<div class="split weak"><span class="he small-he">${x.v.hebrew}</span><span>${x.v.meaning}<br><small class="muted">${x.c.errors} error(es) · ${formatInterval(x.c.interval)}</small></span></div>`).join(''):'<p class="muted">Todavía no hay suficientes datos para detectar debilidades.</p>'; $('#activityText').textContent=`${state.activeDays.length} días con actividad registrados. Racha actual: ${state.streak}.`;
}

function exportState(){const blob=new Blob([JSON.stringify({app:'Hebreo Vivo',version:'4.5',profile:{id:currentProfileId,name:currentProfileName},exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='hebreo-vivo-progreso.json';a.click();URL.revokeObjectURL(a.href)}
function importState(file){const r=new FileReader();r.onload=async()=>{try{const x=JSON.parse(r.result);if(!x.state||!x.state.cards)throw Error('Formato no reconocido');state={...structuredClone(DEFAULT),...x.state,skills:{...DEFAULT.skills,...x.state.skills},settings:{...DEFAULT.settings,...x.state.settings}};await save();applySettings();alert('Progreso importado correctamente en el perfil actual.')}catch(e){alert('No se pudo importar: '+e.message)}};r.readAsText(file)}
function setupInstall(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();deferredInstall=null;$('#installBtn').hidden=true}}
function showProfileGate(){
 const gate=$('#profileGate'); if(!gate)return;
 profiles().then(p=>{
   gate.classList.remove('hidden');
   gate.innerHTML=`<div class="profile-gate-card"><span class="eyebrow">Hebreo Vivo</span><h1>¿Quién va a estudiar?</h1><p class="muted">Elige un perfil local. No necesitas correo electrónico. Cada perfil conserva su propio curso, SRS y estadísticas.</p><div class="gate-list">${p.map(x=>`<button class="profile-gate-option ${x.id===currentProfileId?'current':''}" data-profile-id="${x.id}"><span>${x.name}</span>${x.id===currentProfileId?'<small>perfil actual</small>':''}</button>`).join('')}</div><div class="row"><input id="gateNewProfile" maxlength="28" placeholder="Crear nuevo usuario"><button class="primary" id="gateCreateProfile">Crear</button></div><button class="secondary wide" id="gateContinue">Continuar con ${currentProfileName||'este perfil'}</button></div>`;
   $$('.profile-gate-option').forEach(b=>b.onclick=async()=>{await switchProfile(b.dataset.profileId);showProfileGate()});
   $('#gateCreateProfile').onclick=async()=>{const name=$('#gateNewProfile').value;await createProfile(name);showProfileGate()};
   $('#gateContinue').onclick=()=>gate.classList.add('hidden');
 });
}

async function init(){try{await loadData();await ensureProfile();const old=await dbGet();if(old)state={...structuredClone(DEFAULT),...old,skills:{...DEFAULT.skills,...old.skills},settings:{...DEFAULT.settings,...old.settings}};applySettings();renderProfilePanel();renderGlobal();showProfileGate();setupInstall();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});}catch(e){document.body.innerHTML=`<main class="wrap"><div class="card"><h1>No se pudieron cargar los datos.</h1><p>${e.message}</p></div></main>`}}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));
$('#goDay').onclick=()=>{const n=Math.min(180,Math.max(1,Number($('#dayInput').value)||1));state.day=n;lesson=null;save();renderCourse()};$('#exportBtn').onclick=exportState;$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>e.target.files[0]&&importState(e.target.files[0]);$('#storageInfo').onclick=()=>alert(`IndexedDB: activo\nUnidades: ${DATA.vocab.length}\nTarjetas con historial: ${Object.keys(state.cards).length}\nActividad registrada: ${state.activeDays.length} días`);$('#largeText').onchange=e=>{state.settings.largeText=e.target.checked;document.body.classList.toggle('large-he',e.target.checked);save()};$('#reduceMotion').onchange=e=>{state.settings.reduceMotion=e.target.checked;document.body.classList.toggle('reduce-motion',e.target.checked);save()};$('#haptic').onchange=e=>{state.settings.haptic=e.target.checked;save()};$('#resetBtn').onclick=resetCurrentProfile;
init();
