const DB='mikhael-v5.4.2',VER=1,STORE='profiles',META='meta';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const DEFAULT={activeDays:[],streak:0,lastActive:null,completedLessons:[],cards:{},history:[],grammarMastery:{},skills:{comprension:0,reconocimiento:0,produccion:0},settings:{largeText:false,reduceMotion:false,haptic:true},readerDone:{},courseStartedAt:null,reviewSessionNo:0};
let D={curr:null,vocab:[],units:[],sessions:[],phrases:[],ctxGrammar:[],exercises:{},blocks:[],alphabet:[],vocal:[],reader:[],morph:[],grammarFull:[],readerVocab:[]};
let state=structuredClone(DEFAULT),profileId=null,profileName='',currentView='home',selectedUnitId=null,selectedSessionId=null,lessonState={step:0,done:{},writing:[],item:0,writingComplete:false};
let review={queue:[],cursor:0,ratings:{},sessionNo:0,started:false};let deferred=null;
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function load(){const names=['block1-content','alphabet','vocalization','reader','morphology','grammar','reader-vocab'];const vals=await Promise.all(names.map(n=>fetch(`./data/${n}.json`).then(r=>{if(!r.ok)throw Error(`No se pudo cargar ${n}.json`);return r.json()})));[D.curr,D.alphabet,D.vocal,D.reader,D.morph,D.grammarFull,D.readerVocab]=vals;D.vocab=D.curr.vocab;D.units=D.curr.units;D.sessions=D.curr.sessions;D.phrases=D.curr.phrases;D.ctxGrammar=D.curr.contextualGrammar;D.exercises=D.curr.exercises;D.blocks=D.curr.blocks||[]}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE);if(!db.objectStoreNames.contains(META))db.createObjectStore(META)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function metaGet(k){const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction(META).objectStore(META).get(k);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function metaPut(k,v){const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction(META,'readwrite').objectStore(META).put(v,k);q.onsuccess=res;q.onerror=()=>rej(q.error)})}
async function dbGet(){if(!profileId)return null;const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction(STORE).objectStore(STORE).get(profileId);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)})}
async function dbPut(){const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).put(state,profileId);q.onsuccess=res;q.onerror=()=>rej(q.error)})}
async function initProfiles(){let p=await metaGet('profiles')||[],a=await metaGet('activeProfile');if(!p.length){const id='p_'+Date.now();p=[{id,name:'Mi perfil',createdAt:Date.now()}];a=id;await metaPut('profiles',p);await metaPut('activeProfile',a)}profileId=a||p[0].id;const x=p.find(z=>z.id===profileId)||p[0];profileId=x.id;profileName=x.name;const old=await dbGet();if(old)state={...structuredClone(DEFAULT),...old,skills:{...DEFAULT.skills,...old.skills},settings:{...DEFAULT.settings,...old.settings},grammarMastery:old.grammarMastery||{},cards:old.cards||{},completedLessons:old.completedLessons||[],reviewSessionNo:old.reviewSessionNo||0}}
function today(){return new Date().toISOString().slice(0,10)}
function touch(){const d=today();if(!state.activeDays.includes(d))state.activeDays.push(d);if(state.lastActive!==d){const y=new Date();y.setDate(y.getDate()-1);const yd=y.toISOString().slice(0,10);state.streak=state.lastActive===yd?state.streak+1:1;state.lastActive=d}}
function vocab(id){return D.vocab.find(v=>v.id===id)||D.readerVocab.find(v=>v.id===id)}
function courseVocab(id){return D.vocab.find(v=>v.id===id)}
function unit(id){return D.units.find(u=>u.id===id)}
function session(id){return D.sessions.find(s=>s.id===id)}
function sessionsForUnit(uid){return D.sessions.filter(s=>s.unitId===uid)}
function phrase(id){return D.phrases.find(p=>p.id===id)}
function grammar(id){return D.ctxGrammar.find(g=>g.id===id)}
function card(id){return state.cards[id]||(state.cards[id]={id,created:Date.now(),firstSeen:Date.now(),lastReview:null,status:'new',nextReviewSession:state.reviewSessionNo+1,regularUntil:0,regularWeight:0,reps:0,errors:0,againCount:0,lastRating:null})}
function introduce(ids){let changed=false;(ids||[]).filter(Boolean).forEach(id=>{if(courseVocab(id)&&!state.cards[id]){card(id);changed=true}});return changed}
function ensureLessonCards(s){if(introduce(s.targetVocabIds||[])){dbPut().catch(()=>{})}}
function grammarPriority(id){const m=Number(state.grammarMastery[id]||0);return m===1?30:m===2?10:0}
function cardScore(c){let s=c.errors*20+grammarPriorityForCard(c.id);if(c.status==='new')s+=10;if(c.lastRating===0)s+=25;if(c.lastRating===1)s+=20;if(c.lastRating===2)s+=10;return s}
function grammarPriorityForCard(id){return D.sessions.filter(s=>(s.targetVocabIds||[]).includes(id)).flatMap(s=>s.grammarIds||[]).reduce((a,g)=>a+grammarPriority(g),0)}
function save(){return dbPut().then(()=>renderGlobal())}
function prereqMet(u){return (u.prerequisites||[]).every(id=>sessionsForUnit(id).every(s=>state.completedLessons.includes(s.id)))}
function unitUnlocked(u){return prereqMet(u)}
function nextSession(){for(const u of D.units){if(!unitUnlocked(u))continue;const s=sessionsForUnit(u.id).find(x=>!state.completedLessons.includes(x.id));if(s)return s}return null}
function show(view){currentView=view;$$('.view').forEach(x=>x.classList.toggle('hidden',x.id!==view));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='course')renderCourse();if(view==='review')renderReview();if(view==='reader')renderReader();if(view==='alphabet')renderAlphabet();if(view==='grammar')renderGrammar();if(view==='stats')renderStats();if(view==='settings')renderProfilePanel();renderGlobal();scrollTo({top:0,behavior:'auto'})}
function renderGlobal(){const due=eligibleReviewCards(false).length;$('#profileName').textContent=profileName;$('#dueBadge').textContent=due;$('#mobileDue').textContent=due;$('#homeDay').textContent=state.activeDays.length;$('#homeDue').textContent=due;$('#homeDueInline').textContent=due;$('#homeStreak').textContent=state.streak;const n=nextSession();$('#homeGoal').textContent=n?`${unit(n.unitId)?.title||''} · ${n.title}`:'Ruta completada';const pct=Math.round(state.completedLessons.length/D.sessions.length*100);$('#dayProgress').style.width=pct+'%';$('#sessionSummary').textContent=`${state.completedLessons.length} de ${D.sessions.length} lecciones completadas · ${pct}% del curso.`;$('#adaptiveAdvice').textContent=due?`Hay ${due} tarjetas disponibles para repaso. Se priorizan errores y conceptos débiles.`:'Elige una unidad y una lección. Puedes hacer varias en un mismo día.'}
function renderCourse(){let u=unit(selectedUnitId);if(!u){const n=nextSession();selectedUnitId=n?.unitId||D.units[0]?.id}u=unit(selectedUnitId);if(!u)return;const ss=sessionsForUnit(u.id);if(!selectedSessionId||!ss.some(s=>s.id===selectedSessionId))selectedSessionId=ss.find(s=>!state.completedLessons.includes(s.id))?.id||ss[0]?.id;const s=session(selectedSessionId);$('#courseTitle').textContent=`Unidad ${u.id} · ${u.title}`;$('#courseObjective').textContent=u.objective;const done=ss.filter(x=>state.completedLessons.includes(x.id)).length;$('#courseMeta').innerHTML=`<span>Bloque 1</span><span>${ss.length} lecciones</span><span>${done}/${ss.length} completadas</span><span>Sin límite diario</span>`;renderUnitNavigator(u);if(s)renderLesson(s,u)}
function renderUnitNavigator(active){const host=$('#unitNavigator');host.innerHTML=D.blocks.map(b=>`<div class="unit-block"><div class="eyebrow">Bloque ${b.id} · ${esc(b.title)}</div><div class="unit-list">${D.units.filter(u=>u.block===b.id).map(u=>{const unlocked=unitUnlocked(u),done=sessionsForUnit(u.id).filter(s=>state.completedLessons.includes(s.id)).length;return `<button class="unit-card ${u.id===active.id?'active':''} ${unlocked?'':'locked'}" data-unit="${u.id}" ${unlocked?'':'disabled'}><div class="unit-title">${esc(u.id)} · ${esc(u.title)}</div><div class="muted small">${esc(u.objective)}</div><div class="unit-meta"><span>${done}/${sessionsForUnit(u.id).length} lecciones</span><span>${unlocked?'Disponible':'Bloqueada'}</span></div></button>`}).join('')}</div></div>`).join('');$$('[data-unit]').forEach(b=>b.onclick=()=>{selectedUnitId=b.dataset.unit;selectedSessionId=sessionsForUnit(selectedUnitId).find(s=>!state.completedLessons.includes(s.id))?.id||sessionsForUnit(selectedUnitId)[0]?.id;lessonState={step:0,done:{},writing:[],item:0,writingComplete:false};renderCourse()});const ss=sessionsForUnit(active.id);host.insertAdjacentHTML('beforeend',`<div class="card unit-lesson-header"><div><h2>Lecciones de ${esc(active.id)}</h2><p class="muted">Puedes hacer una, varias o todas las lecciones de esta unidad en el mismo día. El calendario no limita el avance.</p></div><div class="lesson-list">${ss.map(s=>`<button class="lesson-choice ${s.id===selectedSessionId?'active':''} ${state.completedLessons.includes(s.id)?'done':''}" data-session="${s.id}"><span><b>${esc(s.id)} · ${esc(s.title)}</b><small class="muted">${esc(s.objective)}</small></span><strong>${state.completedLessons.includes(s.id)?'✓':'›'}</strong></button>`).join('')}</div></div>`);$$('[data-session]').forEach(b=>b.onclick=()=>{selectedSessionId=b.dataset.session;lessonState={step:0,done:{},writing:[],item:0,writingComplete:false};renderCourse()})}
function currentExercises(s){return (s.exerciseIds||[]).map(id=>D.exercises[id]).filter(Boolean)}
function currentPhrase(s){return (s.phraseIds||[]).map(phrase).find(Boolean)}
function stripHebrewMarks(form){return String(form||'').normalize('NFD').replace(/[\u0591-\u05C7]/g,'').replace(/[־׃]/g,'').replace(/\s/g,'')}
function tileData(form){const clean=stripHebrewMarks(form);const required=[...clean].filter(ch=>/[\u0590-\u05FF]/.test(ch));const extras=[];for(const ch of 'אבגדהוזחטיכלמנסעפצקרשת')if(!required.includes(ch)&&!extras.includes(ch)){extras.push(ch);if(extras.length===3)break}const all=required.map((ch,i)=>({id:`t${i}`,ch,correct:true})).concat(extras.map((ch,i)=>({id:`x${i}`,ch,correct:false})));for(let i=all.length-1;i>0;i--){const j=(i*17+clean.length*7)%(i+1);[all[i],all[j]]=[all[j],all[i]]}return all.filter(t=>t&&typeof t.ch==='string'&&t.ch.trim())}
function writingTiles(cur){return tileData(cur?.answer||'')}
function writingAnswerChars(form){return [...stripHebrewMarks(form)].filter(ch=>/[\u0590-\u05FF]/.test(ch))}

function lessonItems(cur){return Array.isArray(cur?.items)&&cur.items.length?cur.items:[cur]}
function itemVocabId(item){return item?.targetVocabId||null}
function renderLesson(s,u){ensureLessonCards(s);const ex=currentExercises(s);if(!ex.length){$('#lessonArea').innerHTML='<div class="card">Esta lección no tiene ejercicios válidos.</div>';return}if(lessonState.step>=ex.length)lessonState.step=0;const cur=ex[lessonState.step];const items=lessonItems(cur);const idx=Math.min(Number(lessonState.item||0),items.length-1);const item=items[idx]||items[0];const vid=itemVocabId(item)||cur.targetVocabId;const v=courseVocab(vid);const g=grammar((s.grammarIds||[])[0]);let body='';
if(cur.type==='comprehension'){const done=!!lessonState.done[0];body=`<div class="card exercise-card"><span class="eyebrow">1 · Comprensión · ${idx+1}/${items.length}</span><h2>${esc(item.concept||cur.concept||g?.title||'Comprensión')}</h2><p>${esc(item.conceptExplanation||cur.conceptExplanation||g?.explanation||'Observa la palabra y cómo se construye.')}</p><div class="he big-he">${esc(item.stimulus||v?.form||'')}</div><div class="roman pronunciation">${esc(item.phonetic||v?.translit||'')}</div><button class="secondary wide" id="revealInfo">${done?(idx+1<items.length?'Siguiente palabra →':'Revelado ✓'):'Revelar'}</button><div id="compInfo" class="reveal-box ${done?'':'hidden'}"><h3>${esc(item.reveal?.meaning||v?.meaning||'')}</h3><p><b>Lema:</b> ${esc(item.reveal?.lemma||v?.lemma||v?.form||'—')}</p>${item.reveal?.root?`<p><b>Raíz:</b> ${esc(item.reveal.root)}</p>`:''}<p><b>Categoría:</b> ${esc(item.reveal?.category||v?.category||'—')}</p>${item.reveal?.gender?`<p><b>Género:</b> ${esc(item.reveal.gender)} · <b>Número:</b> ${esc(item.reveal.number||'')}</p>`:''}<p>${esc(item.reveal?.note||v?.note||'')}</p><hr><p><b>Qué ocurre aquí:</b> ${esc(item.reveal?.grammar||g?.explanation||'')}</p>${(item.reveal?.grammarExamples||g?.examples||[]).map(x=>`<div class="grammar-example"><div class="he">${esc(x)}</div></div>`).join('')}</div></div>`}
else if(cur.type==='writing'){const w=items[idx];const tiles=writingTiles(w);const typed=Array.isArray(lessonState.writing)?lessonState.writing:[];const typedText=typed.join('');body=`<div class="card exercise-card"><span class="eyebrow">2 · Escritura · ${idx+1}/${items.length}</span><h2>Escribe la palabra en hebreo</h2><p>${esc(w.instruction)}</p><div class="target-meaning">${esc(v?.meaning||'')}</div><div id="writtenWord" class="he big-he written-word">${esc(typedText)}</div><div class="tile-grid">${tiles.map((t,i)=>`<button type="button" class="tile" data-tile="${i}" aria-label="Letra hebrea ${esc(t.ch)}" ${lessonState.done[1]||lessonState.writingComplete?'disabled':''}>${esc(t.ch)}</button>`).join('')}</div><button type="button" class="secondary" id="clearWriting">Borrar</button><p id="writeFb" class="feedback"></p>${lessonState.writingComplete?`<div class="success-box">✓ Correcto<br><span class="he">${esc(w.displayForm||w.answer)}</span><br><span class="roman">${esc(w.phonetic||v?.translit||'')}</span>${idx+1<items.length?`<br><button type="button" class="primary" id="nextWriting">Siguiente palabra →</button>`:''}</div>`:''}</div>`}
else if(cur.type==='recognition'){const r=items[idx];body=`<div class="card exercise-card"><span class="eyebrow">3 · Reconocimiento · ${idx+1}/${items.length}</span><h2>Reconoce el significado</h2><div class="he big-he">${esc(r.stimulus||v?.form||'')}</div><div class="roman pronunciation">${esc(r.phonetic||v?.translit||'')}</div><div class="choice-list">${r.options.map((o,i)=>`<button class="choice" data-choice="${i}" data-correct="${String(i===r.correctIndex)}" ${lessonState.done[2]?'disabled':''}>${esc(o)}</button>`).join('')}</div><p id="recFb" class="feedback"></p></div>`}
const labels=['Comprensión','Escritura','Reconocimiento'];const last=lessonState.step===2;body+=`<div class="card"><div class="exercise-progress"><button class="secondary" id="prevStep" ${lessonState.step===0?'disabled':''}>← Anterior</button><span class="eyebrow">${labels[lessonState.step]} · ${lessonState.step+1}/3</span><button class="primary" id="nextStep" ${lessonState.done[lessonState.step]?'':'disabled'}>${last?'Finalizar lección':'Continuar →'}</button></div></div>`;$('#lessonArea').innerHTML=body;wireLesson(s,u,cur,idx,items.length)}
function markStepDone(n){lessonState.done[n]=true}
async function wireLesson(s,u,cur,idx,total){const reveal=$('#revealInfo');if(reveal)reveal.onclick=()=>{if(!lessonState.done[0]){lessonState.done[0]=true;renderLesson(s,u)}else if(idx+1<total){lessonState.item=idx+1;lessonState.done[0]=false;renderLesson(s,u)}else{renderLesson(s,u)}};
if(cur.type==='writing'){const w=lessonItems(cur)[idx];const tiles=writingTiles(w);const answer=writingAnswerChars(w.answer);if(!Array.isArray(lessonState.writing))lessonState.writing=[];$$('#lessonArea [data-tile]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.tile),t=tiles[i];if(!t?.ch||lessonState.done[1])return;lessonState.writing.push(t.ch);const n=lessonState.writing.length;const correctSoFar=lessonState.writing.every((ch,j)=>ch===answer[j]);const out=$('#writtenWord');if(out)out.textContent=lessonState.writing.join('');if(!correctSoFar){lessonState.writing=[];const fb=$('#writeFb');if(fb)fb.textContent='Orden incorrecto. Se reinicia el ejercicio.';vibrate(30);setTimeout(()=>renderLesson(s,u),300);return}if(n===answer.length){lessonState.writingComplete=true;if(idx+1>=total){lessonState.done[1]=true;lessonState.item=0;state.skills.produccion++;touch();introduce(cur.targetVocabIds||[])}vibrate(10);save().then(()=>renderLesson(s,u))}});const nextWriting=$('#nextWriting');if(nextWriting)nextWriting.onclick=()=>{lessonState.item=idx+1;lessonState.writing=[];lessonState.writingComplete=false;renderLesson(s,u)};const clear=$('#clearWriting');if(clear)clear.onclick=()=>{lessonState.writing=[];lessonState.writingComplete=false;renderLesson(s,u)}}
if(cur.type==='recognition'){const r=lessonItems(cur)[idx];$$('#lessonArea [data-choice]').forEach(b=>b.onclick=async()=>{if(lessonState.done[2])return;const ok=b.dataset.correct==='true';if(ok){if(idx+1<total){lessonState.item=idx+1;state.skills.reconocimiento++;touch();introduce([r.targetVocabId]);vibrate(10);await save();renderLesson(s,u)}else{lessonState.done[2]=true;lessonState.item=0;state.skills.reconocimiento++;touch();introduce(cur.targetVocabIds||[]);vibrate(10);const fb=$('#recFb');if(fb)fb.textContent='✓ Correcto. Puedes continuar.';await save();renderLesson(s,u)}}else{b.classList.remove('bad');void b.offsetWidth;b.classList.add('bad');const fb=$('#recFb');if(fb)fb.textContent='No esta vez. Inténtalo de nuevo.';vibrate(30)}})}
$('#prevStep').onclick=()=>{if(lessonState.step>0){lessonState.step--;lessonState.item=0;lessonState.writing=[];lessonState.writingComplete=false;renderLesson(s,u)}};$('#nextStep').onclick=async()=>{if(!lessonState.done[lessonState.step])return;if(lessonState.step<2){lessonState.step++;lessonState.item=0;lessonState.writing=[];lessonState.writingComplete=false;renderLesson(s,u)}else await completeSelectedLesson()}}
async function completeSelectedLesson(){const s=session(selectedSessionId);if(!s)return;const ex=currentExercises(s);if(!ex.every((e,i)=>lessonState.done[i]))return;introduce(s.targetVocabIds||[]);if(!state.completedLessons.includes(s.id)){state.completedLessons.push(s.id);touch();if(!state.courseStartedAt)state.courseStartedAt=Date.now();await save()}lessonState={step:0,done:{},writing:[],item:0,writingComplete:false};const ss=sessionsForUnit(s.unitId);const next=ss.find(x=>!state.completedLessons.includes(x.id));if(next)selectedSessionId=next.id;renderCourse()}
function routeWord(id){const v=courseVocab(id);if(!v)return;const c=state.cards[id];const related=D.sessions.filter(s=>(s.targetVocabIds||[]).includes(id));const phrases=D.phrases.filter(p=>(p.tokens||[]).some(t=>t.vocabId===id));const forms=D.morph.filter(m=>m.surface&&normalize(m.surface)===normalize(v.form));const relatedForms=v.relatedForms||[];$('#routeCard').innerHTML=`<div class="card"><span class="eyebrow">Ruta de aprendizaje · ${esc(id)}</span><div class="he big-he">${esc(v.form)}</div><div class="roman">${esc(v.translit||'')}</div><h2>${esc(v.meaning)}</h2><p><b>Lema:</b> ${esc(v.lemma||v.form)} · <b>Categoría:</b> ${esc(v.category||'—')}</p>${v.gender?`<p><b>Género:</b> ${esc(v.gender)} · <b>Número:</b> ${esc(v.number||'')}</p>`:''}${v.root?`<p><b>Raíz:</b> ${esc(v.root)}</p>`:''}<p><b>Familia:</b> ${esc(v.family||'—')}</p><p><b>Unidad:</b> ${esc(v.unitId||related[0]?.unitId||'—')}</p><p><b>Lecciones:</b> ${related.map(s=>esc(s.id)).join(', ')||'—'}</p>${relatedForms.length?`<p><b>Formas relacionadas:</b> ${relatedForms.map(x=>esc(x)).join(', ')}</p>`:''}<p><b>Frases:</b> ${phrases.map(p=>esc(p.text)).join(' · ')||'—'}</p>${forms.length?`<div class="morph-card"><b>Morfología disponible</b>${forms.map(m=>`<div class="morph-grid"><div><b>Forma</b><span class="he morph-he">${esc(m.surface)}</span></div><div><b>Lema</b><span>${esc(m.lemma||'—')}</span></div><div><b>Raíz</b><span>${esc(m.root||'—')}</span></div><div><b>Análisis</b><span>${esc(m.morphology||'—')}</span></div></div><p class="morph-note">${esc(m.note||m.gloss||'')}</p>`).join('')}</div>`:''}<hr><p><b>Estado del Banco:</b> ${c?'vista / en aprendizaje':'no vista aún'}</p>${c?`<p><b>Repasos:</b> ${c.reps} · <b>Errores:</b> ${c.errors} · <b>Última valoración:</b> ${esc(c.lastRating||'—')}</p>`:''}<p>${esc(v.note||'')}</p></div>`;show('stats')}
function reviewEligible(c,n){if(c.status==='mastered')return false;if(c.status==='new')return n>=Number(c.nextReviewSession||1);if(c.status==='again')return n>=Number(c.nextReviewSession||n);if(c.status==='mal')return n===Number(c.nextReviewSession);if(c.status==='regular')return n>=Number(c.nextReviewSession)&&n<=Number(c.regularUntil);return false}
function eligibleReviewCardsFor(n,randomizeRegular=true){const arr=[];for(const c of Object.values(state.cards)){const v=courseVocab(c.id);if(!v)continue;if(reviewEligible(c,n)){if(randomizeRegular&&c.status==='regular'){const p=Math.max(.15,Number(c.regularWeight||.72));if(Math.random()>p)continue}arr.push(v)}}arr.sort((a,b)=>cardScore(card(b.id))-cardScore(card(a.id)));return arr}
function eligibleReviewCards(randomizeRegular=true){return eligibleReviewCardsFor(state.reviewSessionNo+1,randomizeRegular)}
function renderReview(){if(!review.started){const q=eligibleReviewCards(false);$('#reviewCount').textContent=q.length;$('#reviewCard').innerHTML=q.length?`<div class="card"><h2>Iniciar sesión de repaso</h2><p>Hay ${q.length} tarjetas de palabras que ya has visto en las lecciones.</p><button class="primary wide" id="startReview">Comenzar repaso</button><p class="muted small">El Banco conserva todas las tarjetas aunque dejen de aparecer en el repaso normal.</p></div>`:`<div class="card"><h2>No hay tarjetas pendientes.</h2><p class="muted">Las palabras nuevas entrarán al repaso después de haber sido vistas en las lecciones.</p><button class="secondary" data-view="course">Volver al curso</button></div>`;const st=$('#startReview');if(st)st.onclick=()=>{const n=state.reviewSessionNo+1;const q=eligibleReviewCardsFor(n,true);state.reviewSessionNo=n;review={queue:q,cursor:0,ratings:{},ratingsCount:0,sessionNo:n,started:true};save().then(renderReview)};return}const q=review.queue;if(!q.length||review.cursor>=q.length){review.started=false;save();renderReview();return}const v=q[review.cursor],c=card(v.id),rated=review.ratings[v.id]!==undefined;$('#reviewCount').textContent=Math.max(0,q.length-(review.ratingsCount||0));$('#reviewCard').innerHTML=`<div class="eyebrow">Sesión ${review.sessionNo} · Tarjeta ${review.cursor+1} de ${q.length}</div><div class="he big-he">${esc(v.form)}</div><div class="review-reveal"><button class="secondary" id="revealPhonetic">Fonética</button><button class="secondary" id="revealMeaning">Significa</button><div id="rphon" class="roman hidden">${esc(v.translit||'')}</div><div id="rmean" class="meaning hidden">${esc(v.meaning||'')}</div></div><div id="reviewRating" class="rating-box hidden"><p>¿Cómo te fue?</p><div class="review-actions"><button class="secondary" data-rating="again">Otra vez</button><button class="danger" data-rating="mal">Mal</button><button class="secondary" data-rating="regular">Regular</button><button class="primary" data-rating="bien">Bien</button></div></div><p class="muted small">Repasos: ${c.reps} · Errores: ${c.errors}</p><div class="review-nav"><button class="secondary" id="rprev" ${review.cursor===0?'disabled':''}>← Anterior</button></div><div class="card bank-link"><button class="ghost-dark" data-bank="${esc(v.id)}">Ver ficha completa en Banco / Ruta</button></div>`;$('#revealPhonetic').onclick=()=>{$('#rphon').classList.remove('hidden');maybeRating()};$('#revealMeaning').onclick=()=>{$('#rmean').classList.remove('hidden');maybeRating()};function maybeRating(){if(!$('#rphon').classList.contains('hidden')&& !$('#rmean').classList.contains('hidden'))$('#reviewRating').classList.remove('hidden')}$('#rprev').onclick=()=>{if(review.cursor>0){review.cursor--;renderReview()}};$$('[data-rating]').forEach(b=>b.onclick=()=>rateReview(b.dataset.rating));const bl=$('[data-bank]');if(bl)bl.onclick=()=>routeWord(bl.dataset.bank)}
async function rateReview(kind){const v=review.queue[review.cursor];if(!v||review.ratings[v.id]!==undefined)return;const c=card(v.id),now=Date.now();c.lastReview=now;c.reps++;c.lastRating=kind;c.nextReviewSession=review.sessionNo+1;touch();if(kind==='again'){c.status='again';c.nextReviewSession=review.sessionNo;c.againCount=(c.againCount||0)+1;review.queue.push(v)}else if(kind==='mal'){c.status='mal';c.nextReviewSession=review.sessionNo+1;c.regularUntil=0;c.regularWeight=0;c.errors++}else if(kind==='regular'){c.status='regular';c.nextReviewSession=review.sessionNo+1;c.regularUntil=review.sessionNo+3;c.regularWeight=.72}else if(kind==='bien'){c.status='mastered';c.nextReviewSession=Number.MAX_SAFE_INTEGER;c.regularUntil=0;c.regularWeight=0}state.history.push({ts:now,id:v.id,rating:kind,session:review.sessionNo});if(state.history.length>3000)state.history=state.history.slice(-3000);review.ratings[v.id]=kind;review.ratingsCount=(review.ratingsCount||0)+1;await save();review.cursor++;renderReview()}
function renderBank(){const seen=D.vocab.filter(v=>state.cards[v.id]);const host=$('#bankList');host.innerHTML=seen.length?seen.map(v=>{const c=card(v.id);return `<button class="bank-item" data-bank="${esc(v.id)}"><span class="he">${esc(v.form)}</span><span><b>${esc(v.meaning)}</b><small class="muted">${esc(v.translit||'')} · ${c.status==='mastered'?'Dominada':c.status==='new'?'Nueva':c.status}</small></span><strong>›</strong></button>`}).join(''):'<p class="muted">Aún no hay tarjetas en el Banco. Aparecerán al completar lecciones.</p>';$$('[data-bank]').forEach(b=>b.onclick=()=>routeWord(b.dataset.bank))}
function readerVocab(id){return D.readerVocab.find(v=>v.id===id)||null}
function renderReader(){const level=1,texts=D.reader.filter(t=>t.level===level);$('#readerLevels').innerHTML=[1,2,3,4,5].map(x=>`<span class="${x===level?'':'muted'}">Nivel ${x}${x>level?' · 🔒':''}</span>`).join('');const t=texts[0]||D.reader[0];if(!t){$('#readerText').innerHTML='<div class="card">No hay lecturas.</div>';return}$('#readerText').innerHTML=`<article class="card"><span class="eyebrow">${esc(t.reference||'')}</span><h2>${esc(t.title)}</h2><div class="readerline">${(t.tokens||[]).map((tok,i)=>`<button class="readerword" data-token-index="${i}">${esc(tok.text||tok.surface||'')}</button>`).join(' ')}</div><div class="lesson-actions"><button class="secondary" id="showTranslation">Ver traducción</button><button class="primary" id="finishReader">${state.readerDone[t.id]?'✓ Lectura hecha':'Marcar lectura como hecha'}</button></div><div id="readerTranslation" class="reader-help hidden"><b>Traducción de estudio</b><p>${esc(t.translation||'')}</p></div><div id="readerHelp" class="reader-help">Toca una palabra para ver su ayuda.</div><div class="reader-question"><b>Comprueba comprensión</b><p>${esc(t.question||'')}</p><details><summary>Mostrar respuesta</summary><p><b>${esc(t.answer||'')}</b></p></details></div></article>`;$$('[data-token-index]').forEach(b=>b.onclick=()=>{const tok=t.tokens[Number(b.dataset.tokenIndex)],id=tok.vocab_id||tok.vocabId;const v=courseVocab(id)||readerVocab(id);$('#readerHelp').innerHTML=v?`<b>${esc(v.form||v.hebrew)}</b> · ${esc(v.meaning)}${v.root?` · raíz ${esc(v.root)}`:''}<br><span class="muted small">${esc(v.category||'')}</span>`:'No hay ficha todavía para esta palabra.'});$('#showTranslation').onclick=()=>$('#readerTranslation').classList.remove('hidden');$('#finishReader').onclick=async()=>{state.readerDone[t.id]=true;touch();await save();renderReader()}}
function renderAlphabet(){const finals={כ:'ך',מ:'ם',נ:'ן',פ:'ף',צ:'ץ'};$('#letterGrid').innerHTML=D.alphabet.map(a=>`<div class="letter"><div class="he">${esc(a.char)}</div><b>${esc(a.name)}</b><div class="muted small">${esc(a.sound)}</div>${finals[a.char]?`<div class="final-form"><span class="he">${esc(a.char)}</span><span>→</span><span class="he">${finals[a.char]}</span></div>`:''}</div>`).join('');$('#vocalGrid').innerHTML=D.vocal.map(x=>`<div class="card vocal"><div class="he">${esc(x.mark||x.symbol||'')}</div><h3>${esc(x.name)}</h3><p>${esc(x.approx||x.sound||'')}</p><div class="muted small">${esc(x.example||'')}</div></div>`).join('')}
async function markGrammar(id,val){state.grammarMastery[id]=val;touch();await save();renderGrammar()}
function renderGrammar(){const contextual=D.ctxGrammar.map(g=>{const m=Number(state.grammarMastery[g.id]||0);return `<article class="card grammar-card"><span class="eyebrow">Concepto contextual · ${esc(g.unitId)}</span><h2>${esc(g.title)}</h2><p><b>${esc(g.phenomenon)}</b></p><p>${esc(g.explanation)}</p><div class="grammar-examples">${g.examples.map(e=>`<div class="grammar-example"><div class="he">${esc(e)}</div></div>`).join('')}</div><details><summary>Por qué importa</summary><p>${esc(g.why)}</p></details><div class="notice"><b>¿Cuánto lo comprendes?</b><div class="mastery-buttons"><button class="secondary ${m===3?'selected':''}" data-gm="${g.id}" data-value="3">Bien</button><button class="secondary ${m===2?'selected':''}" data-gm="${g.id}" data-value="2">Regular</button><button class="danger ${m===1?'selected':''}" data-gm="${g.id}" data-value="1">Mal</button></div><p class="muted small">«Mal» aumenta la prioridad de las tarjetas de las lecciones relacionadas en el repaso.</p></div></article>`}).join('');const full=D.grammarFull.map(g=>`<article class="card grammar-card"><span class="eyebrow">Referencia completa</span><h2>${esc(g.title)}</h2><p>${esc(g.summary)}</p><div class="he">${esc(g.example)}</div><p><b>${esc(g.translation)}</b></p><details><summary>Explicación</summary><p>${esc(g.note)}</p>${(g.examples||[]).map(e=>`<div class="grammar-example"><div class="he">${esc(e.hebrew)}</div><b>${esc(e.meaning)}</b><div class="muted small">${esc(e.analysis)}</div></div>`).join('')}</details></article>`).join('');$('#grammarGrid').innerHTML=contextual+`<div class="card"><h2>Referencia gramatical completa</h2><p class="muted">Consulta general, separada de los ejercicios del curso.</p></div>`+full;$$('#grammarGrid [data-gm]').forEach(b=>b.onclick=()=>markGrammar(b.dataset.gm,Number(b.dataset.value)))}
function renderStats(){const total=state.history.length,correct=state.history.filter(x=>x.rating==='bien').length;$('#stSessions').textContent=state.completedLessons.length;$('#stAccuracy').textContent=total?Math.round(correct/total*100)+'%':'0%';$('#stMastered').textContent=Object.values(state.cards).filter(c=>c.status==='mastered').length;$('#stReviews').textContent=total;$('#skillBars').innerHTML=Object.entries(state.skills).map(([k,v])=>`<p><b>${esc(k)}</b></p><div class="progress"><i style="width:${Math.min(100,v)}%"></i></div>`).join('');$('#activityText').textContent=`${state.activeDays.length} días activos · ${state.completedLessons.length}/${D.sessions.length} lecciones completadas · ${Object.keys(state.cards).length} tarjetas en el Banco.`;renderBank()}
function renderProfilePanel(){metaGet('profiles').then(p=>{$('#profilePanel').innerHTML=`<div class="card profile-box"><span class="eyebrow">Perfil local</span><h2>${esc(profileName)}</h2><p class="muted small">Cada perfil mantiene curso, Banco, repaso y progreso por separado.</p><select id="profileSelect">${p.map(x=>`<option value="${x.id}" ${x.id===profileId?'selected':''}>${esc(x.name)}</option>`).join('')}</select><div class="row"><input id="newProfileName" maxlength="28" placeholder="Nuevo usuario"><button class="secondary" id="createProfile">Crear</button></div><button class="secondary" id="resetProfile">Restablecer progreso</button></div>`;$('#profileSelect').onchange=async e=>{profileId=e.target.value;await metaPut('activeProfile',profileId);state=structuredClone(DEFAULT);await initProfiles();renderProfilePanel();show('home')};$('#createProfile').onclick=async()=>{const n=$('#newProfileName').value.trim();if(!n)return;const p=await metaGet('profiles')||[];if(p.some(x=>x.name.toLowerCase()===n.toLowerCase()))return alert('Ese perfil ya existe.');const x={id:'p_'+Date.now(),name:n,createdAt:Date.now()};p.push(x);await metaPut('profiles',p);await metaPut('activeProfile',x.id);await initProfiles();renderProfilePanel();show('home')};$('#resetProfile').onclick=async()=>{if(confirm('¿Restablecer este perfil?')){state=structuredClone(DEFAULT);await save();show('home')}}})}
function setup(){document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)show(b.dataset.view)});$('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({app:'Mikhael',version:'5.4.2',profile:{id:profileId,name:profileName},state},null,2)],{type:'application/json'}));a.download='mikhael-progreso-v5.4.2.json';a.click()};$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{const r=new FileReader();r.onload=async()=>{try{const x=JSON.parse(r.result);state={...structuredClone(DEFAULT),...x.state,skills:{...DEFAULT.skills,...(x.state?.skills||{})},settings:{...DEFAULT.settings,...(x.state?.settings||{})},grammarMastery:x.state?.grammarMastery||{},cards:x.state?.cards||{}};await save();alert('Progreso importado.')}catch(err){alert('No se pudo importar: '+err.message)}};r.readAsText(e.target.files[0])};$('#storageInfo').onclick=()=>navigator.storage?.persist?.().then(ok=>alert(ok?'Almacenamiento persistente solicitado.':'El navegador no confirmó persistencia.'));['largeText','reduceMotion','haptic'].forEach(id=>$('#'+id).onchange=e=>{state.settings[id]=e.target.checked;applySettings();save()});renderProfilePanel()}
function applySettings(){document.body.classList.toggle('large-he',state.settings.largeText);document.body.classList.toggle('reduce-motion',state.settings.reduceMotion);if($('#largeText'))$('#largeText').checked=!!state.settings.largeText;if($('#reduceMotion'))$('#reduceMotion').checked=!!state.settings.reduceMotion;if($('#haptic'))$('#haptic').checked=!!state.settings.haptic}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferred){deferred.prompt();deferred=null;$('#installBtn').hidden=true}};
(async()=>{try{await load();await initProfiles();applySettings();setup();show('home');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});}catch(e){document.body.innerHTML=`<main class="wrap"><div class="card"><h1>Error al cargar Mikhael v5.4.2</h1><p>${esc(e.message)}</p></div></main>`}})();
